version: "3"
services:
    database:
        # $ docker-compose up -d database
        # $ docker exec -it database mongo && db.enableFreeMonitoring()
        container_name: database
        image: mongo:4.2.0
        restart: always
        volumes:
            - ./database:/data/db
        ports:
            - 27017:27017
