name: publish-image
on:
  release:
    types: [published]
jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Pull source code
        uses: actions/checkout@v2.3.4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1.0.2
      - name: Login to DockerHub
        uses: docker/login-action@v1.6.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF##*/}
      - name: Build and push
        uses: docker/build-push-action@v2.1.0
        with:
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/scr-web:${{steps.get_version.outputs.VERSION}},${{secrets.DOCKERHUB_USERNAME}}/scr-web:latest
          platforms: linux/amd64,linux/arm64,linux/386
